/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlateFrame.java
 *
 * Created on Jan 20, 2012, 4:32:52 PM
 */
package be.ugent.maf.limsdesktop.gui.plate;

import be.ugent.maf.limsdesktop.entity.PlateFormat;
import be.ugent.maf.limsdesktop.service.PlateService;
import be.ugent.maf.limsdesktop.spring.ApplicationContextProvider;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import javax.persistence.PersistenceException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.SwingBindings;
import org.springframework.context.ApplicationContext;

/**
 *
 * @author Paola
 */
public class PlateFrame extends javax.swing.JFrame implements ComponentListener {

    private PlateService plateService;
    private ObservableList<PlateFormat> plateFormatBindingList;
    private BindingGroup bindingGroup;
    private PlatePanel platePanel;

    /** Creates new form PlateFrame */
    public PlateFrame() {
        initComponents();

        //load applicationContext
        ApplicationContext context = ApplicationContextProvider.getInstance().getApplicationContext();
        plateService = (PlateService) context.getBean("plateService");

        //init plateFormatJcombo
        plateFormatBindingList = ObservableCollections.observableList(plateService.findAll());
        JComboBoxBinding jComboBoxBinding = SwingBindings.createJComboBoxBinding(UpdateStrategy.READ_WRITE, plateFormatBindingList, plateFormatComboBox);
        bindingGroup = new BindingGroup();
        bindingGroup.addBinding(jComboBoxBinding);
        bindingGroup.bind();
        plateFormatComboBox.setSelectedIndex(-1);

        addComponentListener(this);

        //create new platePanel
        platePanel = new PlatePanel();
        jPanel2.add(platePanel);

        ActionListener actionListener = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent evt) {
                if (plateFormatComboBox.getSelectedIndex() != -1) {
                    PlateFormat selectedPlateFormat = plateFormatBindingList.get(plateFormatComboBox.getSelectedIndex());
                    Dimension parentDimension = jPanel2.getSize();
                    platePanel.initPanel(selectedPlateFormat.getNumberOfCols(), selectedPlateFormat.getNumberOfRows(), parentDimension);
                    repaint();
                }
            }
        };

        plateFormatComboBox.addActionListener(actionListener);
    }

    @Override
    public void componentResized(ComponentEvent e) {
        platePanel.doResize(jPanel2.getSize());
    }

    @Override
    public void componentMoved(ComponentEvent e) {
    }

    @Override
    public void componentShown(ComponentEvent e) {
    }

    @Override
    public void componentHidden(ComponentEvent e) {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        numberOfRowsTextField = new javax.swing.JTextField();
        addPlateFormatButton = new javax.swing.JToggleButton();
        plateFormatComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        numberOfColsTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plate");
        setMinimumSize(new java.awt.Dimension(600, 700));
        setName("plateFrame"); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setAutoscrolls(true);

        addPlateFormatButton.setText("add plate format");
        addPlateFormatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlateFormatButtonActionPerformed(evt);
            }
        });

        plateFormatComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("insert number of columns");

        jLabel3.setText("insert number of rows");

        jLabel1.setText("select a plate format ");

        numberOfColsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfColsTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberOfColsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberOfRowsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(addPlateFormatButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(plateFormatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(numberOfColsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(numberOfRowsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(addPlateFormatButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plateFormatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addPlateFormatButton, jLabel1, jLabel2, jLabel3, numberOfColsTextField, numberOfRowsTextField, plateFormatComboBox});

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 11, 16);
        getContentPane().add(jPanel1, gridBagConstraints);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numberOfColsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfColsTextFieldActionPerformed
        // TODO add your handling code here:}//GEN-LAST:event_numberOfColsTextFieldActionPerformed
    }

        private void addPlateFormatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlateFormatButtonActionPerformed

        // TODO add your handling code here:         if (!numberOfColsTextField.getText().isEmpty() && !numberOfRowsTextField.getText().isEmpty()) {             try {                 PlateFormat plateFormat = new PlateFormat();                 plateFormat.setNumberOfCols(Integer.parseInt(numberOfColsTextField.getText()));                 plateFormat.setNumberOfRows(Integer.parseInt(numberOfRowsTextField.getText()));                 plateFormat.setFormat(plateFormat.getNumberOfCols() * plateFormat.getNumberOfRows());                 plateService.save(plateFormat);                 // add to the JComboBox too                 plateFormatBindingList.add(plateFormat);                 numberOfColsTextField.setText("");                 numberOfRowsTextField.setText("");             } // handle ConstraintViolationException             catch (PersistenceException e) {                 // popup an error message                 JOptionPane.showMessageDialog(this, "Plate format already present in the db", "Create new plate format problem", JOptionPane.ERROR_MESSAGE);                 numberOfColsTextField.setText("");                 numberOfRowsTextField.setText("");             }         } else {             JOptionPane.showMessageDialog(this, "Please insert data for a new plate format", "Create new plate format problem", JOptionPane.ERROR_MESSAGE);         }     }//GEN-LAST:event_addPlateFormatButtonActionPerformed
        if (!numberOfColsTextField.getText().isEmpty() && !numberOfRowsTextField.getText().isEmpty()) {
            try {
                PlateFormat plateFormat = new PlateFormat();
                plateFormat.setNumberOfCols(Integer.parseInt(numberOfColsTextField.getText()));
                plateFormat.setNumberOfRows(Integer.parseInt(numberOfRowsTextField.getText()));
                plateFormat.setFormat(plateFormat.getNumberOfCols() * plateFormat.getNumberOfRows());
                plateService.save(plateFormat);
                // add to the JComboBox too                 
                plateFormatBindingList.add(plateFormat);
                numberOfColsTextField.setText("");
                numberOfRowsTextField.setText("");
            } // handle ConstraintViolationException            
            catch (PersistenceException e) {
                // popup an error message                 
                JOptionPane.showMessageDialog(this, "Plate format already present in the db", "Create new plate format problem", JOptionPane.ERROR_MESSAGE);
                numberOfColsTextField.setText("");
                numberOfRowsTextField.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please insert data for a new plate format", "Create new plate format problem", JOptionPane.ERROR_MESSAGE);
        }
    }
//    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PlateFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addPlateFormatButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField numberOfColsTextField;
    private javax.swing.JTextField numberOfRowsTextField;
    private javax.swing.JComboBox plateFormatComboBox;
    // End of variables declaration//GEN-END:variables
}
