/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserPanel.java
 *
 * Created on Mar 28, 2012, 5:42:21 PM
 */
package be.ugent.maf.cellmissy.gui.user;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Paola
 */
public class UserPanel extends javax.swing.JPanel {

    /** Creates new form UserPanel */
    public UserPanel() {
        initComponents();
    }

    public JButton getCreateUserButton() {
        return createUserButton;
    }

    public JTextField getCreateUserEmailTextField() {
        return createUserEmailTextField;
    }

    public JTextField getCreateUserFirstNameTextField() {
        return createUserFirstNameTextField;
    }

    public JTextField getCreateUserLastNameTextField() {
        return createUserLastNameTextField;
    }

    public JButton getDeleteUserButton() {
        return deleteUserButton;
    }

    public JTextField getDeleteUserEmailTextField() {
        return deleteUserEmailTextField;
    }

    public JTextField getDeleteUserFirstNameTextField() {
        return deleteUserFirstNameTextField;
    }

    public JTextField getDeleteUserLastNameTextField() {
        return deleteUserLastNameTextField;
    }

    public JButton getSearchUserButton() {
        return searchUserButton;
    }

    public JTextField getSearchUserFirstNameTextField() {
        return searchUserFirstNameTextField;
    }

    public JTextField getSearchUserLastNameTextField() {
        return searchUserLastNameTextField;
    }

    public JList getUserJList() {
        return userJList;
    }

    public JPasswordField getPasswordField() {
        return passwordField;
    }

    public JComboBox getRoleComboBox() {
        return roleComboBox;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        CreateUserPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        createUserFirstNameTextField = new javax.swing.JTextField();
        createUserLastNameTextField = new javax.swing.JTextField();
        createUserEmailTextField = new javax.swing.JTextField();
        createUserButton = new javax.swing.JButton();
        roleComboBox = new javax.swing.JComboBox();
        selectRoleLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        SearchUserPanel = new javax.swing.JPanel();
        searchUserButton = new javax.swing.JButton();
        searchUserFirstNameTextField = new javax.swing.JTextField();
        firstNameLabel1 = new javax.swing.JLabel();
        lastNameLabel1 = new javax.swing.JLabel();
        searchUserLastNameTextField = new javax.swing.JTextField();
        DeleteUserPanel = new javax.swing.JPanel();
        deleteUserButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userJList = new javax.swing.JList();
        firstNameLabel2 = new javax.swing.JLabel();
        deleteUserFirstNameTextField = new javax.swing.JTextField();
        lastNameLabel2 = new javax.swing.JLabel();
        deleteUserLastNameTextField = new javax.swing.JTextField();
        emailLabel1 = new javax.swing.JLabel();
        deleteUserEmailTextField = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        CreateUserPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Create User"));

        firstNameLabel.setText("First Name");

        lastNameLabel.setText("Last Name");

        emailLabel.setText("Email Address");

        createUserButton.setText("Create User");

        selectRoleLabel.setText("Select a Role");

        jLabel1.setText("Password");

        javax.swing.GroupLayout CreateUserPanelLayout = new javax.swing.GroupLayout(CreateUserPanel);
        CreateUserPanel.setLayout(CreateUserPanelLayout);
        CreateUserPanelLayout.setHorizontalGroup(
            CreateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CreateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateUserPanelLayout.createSequentialGroup()
                        .addGroup(CreateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel)
                            .addComponent(lastNameLabel)
                            .addComponent(emailLabel))
                        .addGap(34, 34, 34)
                        .addGroup(CreateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createUserEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CreateUserPanelLayout.createSequentialGroup()
                                .addGroup(CreateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createUserFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(createUserLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(CreateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(selectRoleLabel)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(CreateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(72, Short.MAX_VALUE))
                    .addGroup(CreateUserPanelLayout.createSequentialGroup()
                        .addComponent(createUserButton)
                        .addContainerGap(385, Short.MAX_VALUE))))
        );

        CreateUserPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {createUserEmailTextField, createUserFirstNameTextField, createUserLastNameTextField});

        CreateUserPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, selectRoleLabel});

        CreateUserPanelLayout.setVerticalGroup(
            CreateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateUserPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(CreateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateUserPanelLayout.createSequentialGroup()
                        .addGroup(CreateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createUserFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectRoleLabel)
                            .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CreateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CreateUserPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(createUserLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createUserEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreateUserPanelLayout.createSequentialGroup()
                        .addComponent(firstNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lastNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(emailLabel)))
                .addGap(18, 18, 18)
                .addComponent(createUserButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CreateUserPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {createUserEmailTextField, createUserFirstNameTextField, createUserLastNameTextField});

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(CreateUserPanel, gridBagConstraints);

        SearchUserPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Search User"));

        searchUserButton.setText("Search User");

        firstNameLabel1.setText("First Name");

        lastNameLabel1.setText("Last Name");

        javax.swing.GroupLayout SearchUserPanelLayout = new javax.swing.GroupLayout(SearchUserPanel);
        SearchUserPanel.setLayout(SearchUserPanelLayout);
        SearchUserPanelLayout.setHorizontalGroup(
            SearchUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchUserPanelLayout.createSequentialGroup()
                        .addComponent(firstNameLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(searchUserFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SearchUserPanelLayout.createSequentialGroup()
                        .addComponent(lastNameLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(searchUserLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(searchUserButton)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        SearchUserPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {searchUserFirstNameTextField, searchUserLastNameTextField});

        SearchUserPanelLayout.setVerticalGroup(
            SearchUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchUserPanelLayout.createSequentialGroup()
                .addGroup(SearchUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchUserPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(SearchUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameLabel1)
                            .addComponent(searchUserFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SearchUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastNameLabel1)
                            .addComponent(searchUserLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SearchUserPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(searchUserButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(SearchUserPanel, gridBagConstraints);

        DeleteUserPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Delete User"));

        deleteUserButton.setText("Delete User");

        userJList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(userJList);

        firstNameLabel2.setText("First Name");

        lastNameLabel2.setText("Last Name");

        emailLabel1.setText("Email Address");

        javax.swing.GroupLayout DeleteUserPanelLayout = new javax.swing.GroupLayout(DeleteUserPanel);
        DeleteUserPanel.setLayout(DeleteUserPanelLayout);
        DeleteUserPanelLayout.setHorizontalGroup(
            DeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(DeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeleteUserPanelLayout.createSequentialGroup()
                        .addGroup(DeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel2)
                            .addComponent(lastNameLabel2)
                            .addComponent(emailLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteUserEmailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(deleteUserFirstNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(deleteUserLastNameTextField)))
                    .addComponent(deleteUserButton))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        DeleteUserPanelLayout.setVerticalGroup(
            DeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteUserPanelLayout.createSequentialGroup()
                .addGroup(DeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DeleteUserPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(DeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteUserPanelLayout.createSequentialGroup()
                                .addComponent(deleteUserFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addGroup(DeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(deleteUserLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastNameLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(DeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deleteUserEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailLabel1)))
                            .addGroup(DeleteUserPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(firstNameLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(deleteUserButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(DeleteUserPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateUserPanel;
    private javax.swing.JPanel DeleteUserPanel;
    private javax.swing.JPanel SearchUserPanel;
    private javax.swing.JButton createUserButton;
    private javax.swing.JTextField createUserEmailTextField;
    private javax.swing.JTextField createUserFirstNameTextField;
    private javax.swing.JTextField createUserLastNameTextField;
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JTextField deleteUserEmailTextField;
    private javax.swing.JTextField deleteUserFirstNameTextField;
    private javax.swing.JTextField deleteUserLastNameTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel firstNameLabel1;
    private javax.swing.JLabel firstNameLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel lastNameLabel1;
    private javax.swing.JLabel lastNameLabel2;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JComboBox roleComboBox;
    private javax.swing.JButton searchUserButton;
    private javax.swing.JTextField searchUserFirstNameTextField;
    private javax.swing.JTextField searchUserLastNameTextField;
    private javax.swing.JLabel selectRoleLabel;
    private javax.swing.JList userJList;
    // End of variables declaration//GEN-END:variables
}
