/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserPanel.java
 *
 * Created on Mar 28, 2012, 5:42:21 PM
 */
package be.ugent.maf.cellmissy.gui;

import be.ugent.maf.cellmissy.entity.User;
import be.ugent.maf.cellmissy.service.UserService;
import be.ugent.maf.cellmissy.spring.ApplicationContextProvider;
import java.util.Set;
import javax.persistence.PersistenceException;
import javax.swing.JOptionPane;
import javax.validation.ConstraintViolation;
import javax.validation.Validation;
import javax.validation.Validator;
import javax.validation.ValidatorFactory;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import org.jdesktop.swingbinding.JListBinding;
import org.jdesktop.swingbinding.SwingBindings;
import org.springframework.context.ApplicationContext;

/**
 *
 * @author Paola
 */
public class UserPanel extends javax.swing.JPanel {

    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    private User newUser;
    private UserService userService;
    private ObservableList<User> userBindingList;

    /** Creates new form UserPanel */
    public UserPanel() {
        initComponents();

        //load applicationContext
        ApplicationContext context = ApplicationContextProvider.getInstance().getApplicationContext();
        userService = (UserService) context.getBean("userService");

        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        //init userJList
        userBindingList = ObservableCollections.observableList(userService.findAll());
        JListBinding jListBinding = SwingBindings.createJListBinding(UpdateStrategy.READ_WRITE, userBindingList, userJList);
        bindingGroup.addBinding(jListBinding);
        bindingGroup.bind();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        CreateUserPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        createUserFirstNameTextField = new javax.swing.JTextField();
        createUserLastNameTextField = new javax.swing.JTextField();
        createUserEmailTextField = new javax.swing.JTextField();
        createUserButton = new javax.swing.JButton();
        SearchUserPanel = new javax.swing.JPanel();
        searchUserButton = new javax.swing.JButton();
        searchUserFirstNameTextField = new javax.swing.JTextField();
        firstNameLabel1 = new javax.swing.JLabel();
        lastNameLabel1 = new javax.swing.JLabel();
        searchUserLastNameTextField = new javax.swing.JTextField();
        DeleteUserPanel = new javax.swing.JPanel();
        deleteUserButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userJList = new javax.swing.JList();
        firstNameLabel2 = new javax.swing.JLabel();
        deleteUserFirstNameTextField = new javax.swing.JTextField();
        lastNameLabel2 = new javax.swing.JLabel();
        deleteUserLastNameTextField = new javax.swing.JTextField();
        emailLabel1 = new javax.swing.JLabel();
        deleteUserEmailTextField = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        firstNameLabel.setText("First Name");

        lastNameLabel.setText("Last Name");

        emailLabel.setText("Email Address");

        createUserButton.setText("Create User");
        createUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreateUserPanelLayout = new javax.swing.GroupLayout(CreateUserPanel);
        CreateUserPanel.setLayout(CreateUserPanelLayout);
        CreateUserPanelLayout.setHorizontalGroup(
            CreateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateUserPanelLayout.createSequentialGroup()
                .addGroup(CreateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateUserPanelLayout.createSequentialGroup()
                        .addGroup(CreateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CreateUserPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(firstNameLabel))
                            .addGroup(CreateUserPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lastNameLabel))
                            .addGroup(CreateUserPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(emailLabel)))
                        .addGap(34, 34, 34)
                        .addGroup(CreateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createUserFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createUserLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createUserEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CreateUserPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(createUserButton)))
                .addContainerGap(272, Short.MAX_VALUE))
        );

        CreateUserPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {createUserEmailTextField, createUserFirstNameTextField, createUserLastNameTextField});

        CreateUserPanelLayout.setVerticalGroup(
            CreateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateUserPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(CreateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createUserFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CreateUserPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(createUserLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createUserEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreateUserPanelLayout.createSequentialGroup()
                        .addComponent(firstNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lastNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(emailLabel)))
                .addGap(18, 18, 18)
                .addComponent(createUserButton)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        CreateUserPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {createUserEmailTextField, createUserFirstNameTextField, createUserLastNameTextField});

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(CreateUserPanel, gridBagConstraints);

        searchUserButton.setText("Search User");
        searchUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchUserButtonActionPerformed(evt);
            }
        });

        firstNameLabel1.setText("First Name");

        lastNameLabel1.setText("Last Name");

        javax.swing.GroupLayout SearchUserPanelLayout = new javax.swing.GroupLayout(SearchUserPanel);
        SearchUserPanel.setLayout(SearchUserPanelLayout);
        SearchUserPanelLayout.setHorizontalGroup(
            SearchUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchUserPanelLayout.createSequentialGroup()
                        .addComponent(firstNameLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(searchUserFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SearchUserPanelLayout.createSequentialGroup()
                        .addComponent(lastNameLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(searchUserLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(searchUserButton)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        SearchUserPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {searchUserFirstNameTextField, searchUserLastNameTextField});

        SearchUserPanelLayout.setVerticalGroup(
            SearchUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchUserPanelLayout.createSequentialGroup()
                .addGroup(SearchUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchUserPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(SearchUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameLabel1)
                            .addComponent(searchUserFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SearchUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastNameLabel1)
                            .addComponent(searchUserLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SearchUserPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(searchUserButton)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(SearchUserPanel, gridBagConstraints);

        deleteUserButton.setText("Delete User");
        deleteUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserButtonActionPerformed(evt);
            }
        });

        userJList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(userJList);

        firstNameLabel2.setText("First Name");

        lastNameLabel2.setText("Last Name");

        emailLabel1.setText("Email Address");

        javax.swing.GroupLayout DeleteUserPanelLayout = new javax.swing.GroupLayout(DeleteUserPanel);
        DeleteUserPanel.setLayout(DeleteUserPanelLayout);
        DeleteUserPanelLayout.setHorizontalGroup(
            DeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(DeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeleteUserPanelLayout.createSequentialGroup()
                        .addGroup(DeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel2)
                            .addComponent(lastNameLabel2)
                            .addComponent(emailLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteUserEmailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(deleteUserFirstNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(deleteUserLastNameTextField)))
                    .addComponent(deleteUserButton))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        DeleteUserPanelLayout.setVerticalGroup(
            DeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteUserPanelLayout.createSequentialGroup()
                .addGroup(DeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DeleteUserPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(DeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteUserPanelLayout.createSequentialGroup()
                                .addComponent(deleteUserFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addGroup(DeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(deleteUserLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastNameLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(DeleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deleteUserEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailLabel1)))
                            .addGroup(DeleteUserPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(firstNameLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(deleteUserButton)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(DeleteUserPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private boolean validateUser(User newUser) {
        boolean isValid = false;

        // validate user entity class
        ValidatorFactory userValidator = Validation.buildDefaultValidatorFactory();
        Validator validator = userValidator.getValidator();
        Set<ConstraintViolation<User>> constraintViolations = validator.validate(newUser);

        if (constraintViolations.isEmpty()) {
            isValid = true;
        } else {
            String message = "";
            for (ConstraintViolation<User> constraintViolation : constraintViolations) {
                message += constraintViolation.getMessage() + "\n";
            }
            JOptionPane.showMessageDialog(this, message, "Validate user problem", JOptionPane.WARNING_MESSAGE);
        }

        return isValid;
    }

    private void resetCreateUserTextFields() {
        // reset create user text fields
        createUserFirstNameTextField.setText("");
        createUserLastNameTextField.setText("");
        createUserEmailTextField.setText("");
    }

    private void createUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserButtonActionPerformed
        // TODO add your handling code here:
        // if user validation was successful, save the new user to the db
        if (validateUser(newUser)) {
            try {
                User savedUser = userService.save(newUser);
                userBindingList.add(savedUser);
                resetCreateUserTextFields();
            } // handle ConstraintViolationException(UniqueConstraint)
            catch (PersistenceException e) {
                JOptionPane.showMessageDialog(this, "User already present in the db", "Create user problem", JOptionPane.ERROR_MESSAGE);
                resetCreateUserTextFields();
            }

        } else {
            resetCreateUserTextFields();
        }
    }//GEN-LAST:event_createUserButtonActionPerformed

    private void searchUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchUserButtonActionPerformed
        // TODO add your handling code here:
        if (!searchUserFirstNameTextField.getText().isEmpty() && !searchUserLastNameTextField.getText().isEmpty()) {
            User user = userService.findByFullName(searchUserFirstNameTextField.getText(), searchUserLastNameTextField.getText());
            if (user != null) {
                JOptionPane.showMessageDialog(this, "User: " + user.getFirstName() + " " + user.getLastName() + ", email: " + user.getEmail() + " was found in the database.", "Search user result", JOptionPane.INFORMATION_MESSAGE);
                searchUserFirstNameTextField.setText("");
                searchUserLastNameTextField.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "No user found", "Search user problem", JOptionPane.INFORMATION_MESSAGE);
                searchUserFirstNameTextField.setText("");
                searchUserLastNameTextField.setText("");
            }
        } else {
            if (!searchUserFirstNameTextField.getText().isEmpty() && searchUserLastNameTextField.getText().isEmpty()) {
                User user = userService.findByFirstName(searchUserFirstNameTextField.getText());
                if (user != null) {
                    JOptionPane.showMessageDialog(this, "User: " + user.getFirstName() + " " + user.getLastName() + ", email: " + user.getEmail() + " was found in the database.", "Search user result", JOptionPane.INFORMATION_MESSAGE);
                    searchUserFirstNameTextField.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "No user found", "Search user problem", JOptionPane.INFORMATION_MESSAGE);
                    searchUserFirstNameTextField.setText("");
                }
            } else {
                if (searchUserFirstNameTextField.getText().isEmpty() && !searchUserLastNameTextField.getText().isEmpty()) {
                    User user = userService.findByLastName(searchUserLastNameTextField.getText());
                    if (user != null) {
                        JOptionPane.showMessageDialog(this, "User: " + user.getFirstName() + " " + user.getLastName() + ", email: " + user.getEmail() + " was found in the database.", "Search user result", JOptionPane.INFORMATION_MESSAGE);
                        searchUserLastNameTextField.setText("");
                    } else {
                        JOptionPane.showMessageDialog(this, "No user found", "Search user problem", JOptionPane.INFORMATION_MESSAGE);
                        searchUserLastNameTextField.setText("");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Please fill in first and/or last name", "Search user problem", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_searchUserButtonActionPerformed

    private void deleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserButtonActionPerformed
        // TODO add your handling code here:
        if (userJList.getSelectedValue() != null) {
            userService.delete((User) userJList.getSelectedValue());
            userBindingList.remove((User) userJList.getSelectedValue());
            deleteUserFirstNameTextField.setText("");
            deleteUserLastNameTextField.setText("");
            deleteUserEmailTextField.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Please select a user to delete", "Delete user problem", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_deleteUserButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateUserPanel;
    private javax.swing.JPanel DeleteUserPanel;
    private javax.swing.JPanel SearchUserPanel;
    private javax.swing.JButton createUserButton;
    private javax.swing.JTextField createUserEmailTextField;
    private javax.swing.JTextField createUserFirstNameTextField;
    private javax.swing.JTextField createUserLastNameTextField;
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JTextField deleteUserEmailTextField;
    private javax.swing.JTextField deleteUserFirstNameTextField;
    private javax.swing.JTextField deleteUserLastNameTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel firstNameLabel1;
    private javax.swing.JLabel firstNameLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel lastNameLabel1;
    private javax.swing.JLabel lastNameLabel2;
    private javax.swing.JButton searchUserButton;
    private javax.swing.JTextField searchUserFirstNameTextField;
    private javax.swing.JTextField searchUserLastNameTextField;
    private javax.swing.JList userJList;
    // End of variables declaration//GEN-END:variables
}
