/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExperimentPanel.java
 *
 * Created on Jan 18, 2012, 9:46:38 AM
 */
package be.ugent.maf.cellmissy.gui;

import be.ugent.maf.cellmissy.entity.Experiment;
import be.ugent.maf.cellmissy.entity.Project;
import be.ugent.maf.cellmissy.parser.ObsepFileParser;
import be.ugent.maf.cellmissy.service.ExperimentService;
import be.ugent.maf.cellmissy.service.ProjectService;
import be.ugent.maf.cellmissy.spring.ApplicationContextProvider;
import java.io.File;
import java.util.List;
import javax.swing.filechooser.FileFilter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import org.jdesktop.swingbinding.JListBinding;
import org.jdesktop.swingbinding.SwingBindings;
import org.springframework.context.ApplicationContext;

/**
 *
 * @author Paola
 */
public class ExperimentPanel extends javax.swing.JFrame {

    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    private ProjectService projectService;
    private ExperimentService experimentService;
    private ObservableList<Project> projectBindingList;
    private ObsepFileParser obsepFileParser;

    /** Creates new form ExperimentPanel */
    public ExperimentPanel() {
        initComponents();

        //load applicationContext
        ApplicationContext context = ApplicationContextProvider.getInstance().getApplicationContext();
        projectService = (ProjectService) context.getBean("projectService");
        experimentService = (ExperimentService) context.getBean("experimentService");
        obsepFileParser = (ObsepFileParser) context.getBean("obsepFileParser");
        
        //init projectJList
        projectBindingList = ObservableCollections.observableList(projectService.findAll());
        JListBinding jListBinding = SwingBindings.createJListBinding(UpdateStrategy.READ_WRITE, projectBindingList, projectJList);
        bindingGroup = new BindingGroup();
        bindingGroup.addBinding(jListBinding);
        bindingGroup.bind();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        projectJList = new javax.swing.JList();
        createExperimentButton = new javax.swing.JButton();
        experimentNumberLabel = new javax.swing.JLabel();
        experimentNumberTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        purposeLabel = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        purposeTextField = new javax.swing.JTextField();
        parseObsepFileButton = new javax.swing.JButton();
        durationLabel = new javax.swing.JLabel();
        durationTextField = new javax.swing.JTextField();
        intervalLabel = new javax.swing.JLabel();
        intervalTextField = new javax.swing.JTextField();
        timeFramesTextField = new javax.swing.JTextField();
        timeFramesLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        projectJList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(projectJList);

        createExperimentButton.setText("create experiment");
        createExperimentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createExperimentButtonActionPerformed(evt);
            }
        });

        experimentNumberLabel.setText("experiment number");

        experimentNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                experimentNumberTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Select a project to create a new experiment");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        dateLabel.setText("date");

        purposeLabel.setText("purpose");

        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });

        purposeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purposeTextFieldActionPerformed(evt);
            }
        });

        parseObsepFileButton.setText("parse obsep file");
        parseObsepFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parseObsepFileButtonActionPerformed(evt);
            }
        });

        durationLabel.setText("duration");

        durationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationTextFieldActionPerformed(evt);
            }
        });

        intervalLabel.setText("interval");

        timeFramesLabel.setText("time frames");

        jLabel1.setText("Please fill in number, date and purpose of the experiment");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createExperimentButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(parseObsepFileButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(timeFramesLabel)
                            .addComponent(durationLabel)
                            .addComponent(intervalLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(durationTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intervalTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeFramesTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateLabel)
                            .addComponent(experimentNumberLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(experimentNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(purposeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(purposeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dateTextField, durationTextField, experimentNumberTextField, intervalTextField, purposeTextField, timeFramesTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(experimentNumberLabel)
                    .addComponent(experimentNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purposeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purposeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(parseObsepFileButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(durationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intervalLabel)
                    .addComponent(intervalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeFramesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeFramesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createExperimentButton)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dateTextField, experimentNumberTextField, purposeTextField});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createExperimentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createExperimentButtonActionPerformed
        // TODO add your handling code here:
        if (projectJList.getSelectedValue() != null && !experimentNumberTextField.getText().isEmpty()) {
            int experimentNumber = Integer.parseInt(experimentNumberTextField.getText());
            File projectFolder = new File(projectJList.getSelectedValue().toString());
            Experiment newExperiment = experimentService.createNewExperiment(experimentNumber, projectFolder);
            try {
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/mm/yyyy");
                Date experimentDate = dateFormat.parse(dateTextField.getText());
                dateTextField.setText("");
                newExperiment.setExperimentDate(experimentDate);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Please insert a date in the format: yyyy/mm/dd", "Experiment date problem", JOptionPane.ERROR_MESSAGE);
                dateTextField.setText("");
            }
            newExperiment.setPurpose(purposeTextField.getText());
            experimentNumberTextField.setText("");
            purposeTextField.setText("");
            newExperiment.setDuration(Double.parseDouble(durationTextField.getText()));
            newExperiment.setExperimentInterval(Double.parseDouble(intervalTextField.getText()));
            newExperiment.setTimeFrames(Double.parseDouble(timeFramesTextField.getText()));
            // save experiment to the db
            experimentService.save(newExperiment);
        }
        durationTextField.setText("");
        intervalTextField.setText("");
        timeFramesTextField.setText("");
    }//GEN-LAST:event_createExperimentButtonActionPerformed

    private void experimentNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_experimentNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_experimentNumberTextFieldActionPerformed

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed

    private void purposeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purposeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purposeTextFieldActionPerformed

    private void parseObsepFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parseObsepFileButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooseObsepFile = new JFileChooser();
        chooseObsepFile.setFileFilter(obsepFilter);

        // in response to the button click, show open dialog 
        int returnVal = chooseObsepFile.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File obsepFile = chooseObsepFile.getSelectedFile();
            obsepFileParser.parseObsepFile(obsepFile);
            List<Double> experimentInfo = obsepFileParser.getExperimentInfo();
            timeFramesTextField.setText(experimentInfo.get(0).toString());
            intervalTextField.setText(experimentInfo.get(1).toString());
            durationTextField.setText(experimentInfo.get(2).toString());
        } else {
            JOptionPane.showMessageDialog(this, "Open command cancelled by user", "Choose obsep file problem", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_parseObsepFileButtonActionPerformed
    private FileFilter obsepFilter = new FileFilter() {
        // to select only (.obsep) files
        @Override
        public boolean accept(File f) {
            return f.getName().toLowerCase().endsWith(".obsep");
        }

        @Override
        public String getDescription() {
            return ("(.obsep)");
        }
    };

    private void durationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExperimentPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExperimentPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExperimentPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExperimentPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ExperimentPanel().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createExperimentButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JTextField durationTextField;
    private javax.swing.JLabel experimentNumberLabel;
    private javax.swing.JTextField experimentNumberTextField;
    private javax.swing.JLabel intervalLabel;
    private javax.swing.JTextField intervalTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton parseObsepFileButton;
    private javax.swing.JList projectJList;
    private javax.swing.JLabel purposeLabel;
    private javax.swing.JTextField purposeTextField;
    private javax.swing.JLabel timeFramesLabel;
    private javax.swing.JTextField timeFramesTextField;
    // End of variables declaration//GEN-END:variables
}