/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProjectPanel.java
 *
 * Created on Dec 14, 2011, 4:57:23 PM
 */
package be.ugent.maf.cellmissy.gui;

import be.ugent.maf.cellmissy.entity.Project;
import be.ugent.maf.cellmissy.service.ProjectService;
import be.ugent.maf.cellmissy.spring.ApplicationContextProvider;
import java.io.File;
import javax.persistence.PersistenceException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import org.jdesktop.swingbinding.JListBinding;
import org.jdesktop.swingbinding.SwingBindings;
import org.springframework.context.ApplicationContext;

/**
 *
 * @author Paola
 */
public class ProjectPanel extends javax.swing.JFrame {

    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    private ProjectService projectService;
    private ObservableList<Project> projectBindingList;

    /** Creates new form ProjectPanel */
    public ProjectPanel() {
        initComponents();

        //load applicationContext
        ApplicationContext context = ApplicationContextProvider.getInstance().getApplicationContext();
        projectService = (ProjectService) context.getBean("projectService");

        //init projectJList
        projectBindingList = ObservableCollections.observableList(projectService.findAll());
        JListBinding jListBinding = SwingBindings.createJListBinding(UpdateStrategy.READ_WRITE, projectBindingList, projectJList);
        bindingGroup = new BindingGroup();
        bindingGroup.addBinding(jListBinding);
        bindingGroup.bind();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createProjectPanel = new javax.swing.JPanel();
        setupProjectNumberLabel = new javax.swing.JLabel();
        setupProjectNumberTextField = new javax.swing.JTextField();
        createProjectButton = new javax.swing.JButton();
        chooseDirectoryButton = new javax.swing.JButton();
        chooseDirectoryTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        projectJList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setupProjectNumberLabel.setText("project number");

        setupProjectNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setupProjectNumberTextFieldActionPerformed(evt);
            }
        });

        createProjectButton.setText("create project");
        createProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProjectButtonActionPerformed(evt);
            }
        });

        chooseDirectoryButton.setText("choose directory");
        chooseDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseDirectoryButtonActionPerformed(evt);
            }
        });

        chooseDirectoryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseDirectoryTextFieldActionPerformed(evt);
            }
        });

        projectJList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(projectJList);

        javax.swing.GroupLayout createProjectPanelLayout = new javax.swing.GroupLayout(createProjectPanel);
        createProjectPanel.setLayout(createProjectPanelLayout);
        createProjectPanelLayout.setHorizontalGroup(
            createProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createProjectPanelLayout.createSequentialGroup()
                .addGroup(createProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createProjectPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(setupProjectNumberLabel)
                        .addGap(18, 18, 18)
                        .addComponent(setupProjectNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createProjectPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(createProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chooseDirectoryTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(createProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createProjectButton)
                            .addComponent(chooseDirectoryButton))))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        createProjectPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {chooseDirectoryButton, createProjectButton, setupProjectNumberTextField});

        createProjectPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {chooseDirectoryTextField, jScrollPane1});

        createProjectPanelLayout.setVerticalGroup(
            createProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createProjectPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(createProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(setupProjectNumberLabel)
                    .addComponent(setupProjectNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(createProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseDirectoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseDirectoryButton))
                .addGroup(createProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createProjectPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createProjectPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(createProjectButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createProjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createProjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupProjectNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setupProjectNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setupProjectNumberTextFieldActionPerformed

    private void chooseDirectoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseDirectoryButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser choosedirectory = new JFileChooser();
        // to select only directories and not files
        choosedirectory.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        // disable the all files option
        choosedirectory.setAcceptAllFileFilterUsed(false);
        // set current directory
        choosedirectory.setCurrentDirectory(new File("C:\\"));
        //in response to the button click, show open dialog 
        int returnVal = choosedirectory.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File projectDirectory = choosedirectory.getSelectedFile();
            chooseDirectoryTextField.setText(projectDirectory.getPath());
        } else {
            JOptionPane.showMessageDialog(this, "Open command cancelled by user", "Choose directory problem", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_chooseDirectoryButtonActionPerformed

    private void createProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProjectButtonActionPerformed
        // TODO add your handling code here:
        if (!setupProjectNumberTextField.getText().isEmpty() && !chooseDirectoryTextField.getText().isEmpty()) {
            // declare parameters for setupProject method
            String projectNumber = setupProjectNumberTextField.getText();
            File projectDirectory = new File(chooseDirectoryTextField.getText());
            try {
                Project savedProject = projectService.setupProject(projectNumber, projectDirectory);
                projectBindingList.add(savedProject);
                setupProjectNumberTextField.setText("");
                chooseDirectoryTextField.setText("");
            } // handle ConstraintViolationException
            catch (PersistenceException e) {
                // popup an error message
                JOptionPane.showMessageDialog(this, "Project already present in the db", "Create project problem", JOptionPane.ERROR_MESSAGE);
                setupProjectNumberTextField.setText("");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Please insert a project number and choose a directory to create a new project", "Create project problem", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_createProjectButtonActionPerformed

    private void chooseDirectoryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseDirectoryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseDirectoryTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ProjectPanel().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseDirectoryButton;
    private javax.swing.JTextField chooseDirectoryTextField;
    private javax.swing.JButton createProjectButton;
    private javax.swing.JPanel createProjectPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList projectJList;
    private javax.swing.JLabel setupProjectNumberLabel;
    private javax.swing.JTextField setupProjectNumberTextField;
    // End of variables declaration//GEN-END:variables
}
